CREATE DATABASE IF NOT EXISTS lifeagent CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lifeagent;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS refresh_tokens (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, token_hash VARCHAR(255) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, revoked TINYINT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

