services:
  life-redis:
    image: redis/redis-stack:latest
    container_name: life-redis
    volumes:
      - redis_data:/data
    networks: [oa_oa]
  life-backend:
    build: ../backend
    container_name: life-backend
    env_file: ../backend/.env
    depends_on:
      life-redis: {condition: service_started}
    networks: [oa_oa]
    volumes:
      - ../backend/uploads:/app/uploads
  life-web:
    build: ../web
    container_name: life-web
    depends_on: [life-backend]
    ports: ["8080:80"]
    networks: [oa_oa]
networks:
  oa_oa:
    external: true
volumes:
  redis_data:
